config/routes.rb
WheresHome::Application.routes.draw do

  resources :applications, except: [:new]
  match 'applications/new/:property_id', to: 'applications#new'
  resources :jobs
  get 'properties/search', to: 'properties#search', as: :properties_search
  resources :properties
  resources :pictures
  resources :locations

  devise_for :sellers, controllers: {
    registrations: "sellers/registrations",
    sessions: 'sellers/sessions'
  }

  devise_for :buyers, controllers: {
    omniauth_callbacks: "buyers/omniauth_callbacks",
    registrations: "buyers/registrations"
  }, skip: [
    :registrations,
    :sessions
  ]

  devise_scope :buyer do
    delete 'buyers/sign_out', to: 'devise/sessions#destroy', as: :destroy_buyer_session
    get 'buyers/edit', to: 'buyers/registrations#edit', as: :edit_buyer_registration
    put 'buyers', to: 'buyers/registrations#update', as: :buyer_registration
  end

  root to: "static_pages#index"
  match 'about', to: "static_pages#about", as: :static_pages_about
  match 'contact', to: "static_pages#contact", as: :static_pages_contact
  match 'landing', to: "static_pages#landing", as: :static_pages_landing
  match 'landlord', to: "static_pages#landlord", as: :static_pages_landlord

end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                :integer          not null, primary key
#  min_price         :integer
#  max_price         :integer
#  sell_type         :integer
#  status            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  min_salary        :integer
#  bedrooms          :integer
#  full_bathrooms    :integer
#  half_bathrooms    :integer
#  available_on      :date
#  pets_allowed      :boolean
#  laundry_available :boolean
#  parking_available :boolean
#  description       :text
#

class Property < ActiveRecord::Base
  attr_accessible :price, :sell_type, :status,
    :bedrooms, :full_bathrooms, :half_bathrooms, :available_on,
    :pets_allowed, :laundry_available, :parking_available,
    :description, :location_attributes

  attr_accessor :min_price, :max_price
  
  validates :price, presence: true,
                        numericality: { only_integer: true }

  has_many :pictures
  has_many :notifications
  has_many :applications
  has_one :location
  accepts_nested_attributes_for :location, :pictures
  
  belongs_to :seller
  validates_associated :location, :pictures
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :require_login, only: [:index, :create, :new, :edit, :update, :destroy]
  before_filter :correct_seller, only: [:edit, :update, :destroy]

  def index
    @properties = current_seller.properties
  end

  def search
    real_params = params[:property] or {
      min_price: '0',
      max_price: '0',
      bedrooms: '0',
      full_bathrooms: '0',
      half_bathrooms: '0',
      location_attributes: {
        city: '',
        state: ''
      }
    }

    if real_params

      scope = Property
      scope = scope.where("#{real_params[:min_price].to_i} <= price") unless real_params[:min_price].blank? or real_params[:min_price].to_i == 0
      scope = scope.where("#{real_params[:max_price].to_i} >= price") unless real_params[:max_price].blank? or real_params[:max_price].to_i == 0
      scope = scope.where("#{real_params[:bedrooms].to_i} == bedrooms") unless real_params[:bedrooms].blank? or real_params[:bedrooms].to_i == 0
      scope = scope.where("#{real_params[:full_bathrooms].to_i} == full_bathrooms") unless real_params[:full_bathrooms].blank? or real_params[:full_bathrooms].to_i == 0
      scope = scope.where("#{real_params[:half_bathrooms].to_i} == half_bathrooms") unless real_params[:half_bathrooms].blank? or real_params[:half_bathrooms].to_i == 0

      @properties = scope.all
      @properties.each do |p|
        if not real_params[:location_attributes][:city].blank? and p.location[:city] != real_params[:location_attributes][:city]
          @properties.delete p
        elsif not real_params[:location_attributes][:state].blank? and p.location[:state].upcase != real_params[:location_attributes][:state].upcase
          @properties.delete p
        end
      end

    else
      @properties = Property.all
    end

    @property = Property.new
    @property.location = Location.new
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
    @property.location = Location.new
  end

  def edit
  end

  def create
    @property = current_seller.properties.build(params[:property])
    if @property.save
      redirect_to @property
    else
      render 'new'
    end
  end

  def update
    if @property.update_attributes(params[:property])
      flash[:success] = "Property updated"
      redirect_to @property
    else
      render 'edit'
    end
  end

  def destroy
    @property.destroy
    flash[:success] = "Property destroyed"
    redirect_to root_url
  end

  private
    def require_login
      unless logged_in?
        flash[:error] = "Only logged in sellers can add a edit their jobs"
        redirect_to root_url
      end
    end

    def correct_seller
      @property = current_seller.properties.find_by_id(params[:id])
      unless @property
        flash[:error] = "You cannot modify a property that you do not own"
        redirect_to root_url
      end
    end

    # 'bool-ize' the current_seller
    def logged_in?
      !!current_seller
    end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>
<div class="margin-left">
  <div class="span5 form-left">
  <%= f.fields_for :location do |l| %>
    <div class="field">
      <%= l.label :address1 %><br />
      <%= l.text_field :address1 %>
    </div>
    <div class="field">
      <%= l.label :address2 %><br />
      <%= l.text_field :address2 %>
    </div>
    <div class="field">
      <%= l.label :city %><br />
      <%= l.text_field :city %>
    </div>
    <div class="field">
      <%= l.label :state %><br />
      <%= l.text_field :state %>
    </div>
    <div class="field">
      <%= l.label :zipcode %><br />
      <%= l.text_field :zipcode %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :sell_type %><br />
    <%= f.select :sell_type, [['Rent', 0], ['Sell', 1]] %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, [['Closed', 0], ['Open', 1]] %>
  </div>



  <div class="field">
    <%= f.label :bedrooms %><br />
    <%= f.text_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :full_bathrooms %><br />
    <%= f.text_field :full_bathrooms %>
  </div>
  <div class="field">
    <%= f.label :half_bathrooms %><br />
    <%= f.text_field :half_bathrooms %>
  </div>
</div>

<div class="span5">
  <div class="field">
    <%= f.label :available_on %><br />
    <%= f.date_select :available_on %>
  </div>
  <div class="field">
    <%= f.label :pets_allowed %><br />
    <%= f.check_box :pets_allowed %>
  </div>
  <div class="field">
    <%= f.label :laundry_available %><br />
    <%= f.check_box :laundry_available %>
  </div>
  <div class="field">
    <%= f.label :parking_available %><br />
    <%= f.check_box :parking_available %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
</div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Property Listings</h1>
<br>
<hr>
<br>
<table style="width: 75%; margin: 0 auto">
  <tr>
    <th style="width: 50%">Location</th>
    <th style="width: 15%">Price</th>
    <th style="width: 15%">Sale type</th>
    <th style="width: 15%">Status</th>
    <th style="width: 5%"></th>
    <th style="width: 5%"></th>
    <th style="width: 5%"></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.location.address1 %> <%= property.location.address2 %>, <%= property.location.city %>, <%= property.location.state %> <%= property.location.zipcode %></td>
    <td><%= property.price %></td>
    <td><%= property.sell_type == 0 ? "Rent" : "Sell" %></td>
    <td><%= property.status == 0 ? "Closed" : "Open" %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

<br><br><br><br><br><br><br><br><br><br><hr><br>

app/views/properties/new.html.erb
<h1 style="margin-left:20px">New Property</h1>
<br>
<hr>
<p style="margin-left:20px">Fill out the form below to submit a new rental property.</p>

<%= render 'form' %>

<%= link_to 'Back to Property Listings', properties_path %>

app/views/properties/search.html.erb
    <div class="span3">
      <div class="side-search">   
        <%= image_tag ('logo2.jpg') %>
        <br><hr><br>
        <p>Search apartment listings</p> 
        <%= form_for @property, url: :properties_search, method: :get do |f| %>
        <div class="navbar-search pull-left">
          <%= f.fields_for :location do |l| %>
          <%= l.text_field :city, placeholder: "City", class: "search-query" %>
          <%= l.text_field :state, placeholder: "State", class: "search-query" %>
          <% end %>
        </div>
        <br><hr class="soften"><br><br><br>
        <p>Price Range</p>
        <div class="form-horizontal">
          <div class="control-group">
            <div class="input-prepend input-append row-fluid">
              <span class="add-on">$</span>
              <%= f.text_field :min_price, placeholder: "Min.", class: "span4", id: "appendedPrependedInput" %>
              <span class="add-on">.00</span>
              <span>&nbsp; Min.</span>
            </div>
            <div class="input-prepend input-append row-fluid">
              <span class="add-on">$</span>
              <%= f.text_field :max_price, placeholder: "Max.", class: "span4", id: "appendedPrependedInput" %>
              <span class="add-on">.00</span>
              <span>&nbsp; Max.</span>
            </div>
          </div>
        </div>

        <br>
        <%= f.label :bedrooms, "Number of Bedrooms", class: "options" %>
        <%= f.select :bedrooms, options_for_select([0,1,2,3,4,5]) %>

        <br>
        <%= f.label :half_bathrooms, "Number of Half Bathrooms", class: "options" %>
        <%= f.select :half_bathrooms, options_for_select([0,1,2,3,4,5]) %>

        <br>
        <%= f.label :full_bathrooms, "Number of Full Bathrooms", class: "options" %>
        <%= f.select :full_bathrooms, options_for_select([0,1,2,3,4,5]) %>

        <br>
        <%= f.label :pets_allowed %>
        <%= f.check_box :pets_allowed, class: "checkbox" %>

        <br>
        <%= f.submit "Where's Home »", class: "btn search-list pull-right" %>
        <% end %>
      </div>
    </div>
    <div class="span7 offset1">
      <p class="lead" style="margin-left:-40px">Listings</p>
      <% @properties.each do |p| %>
        <div class="well well-small">
          <p><b><%= p.location.address1 %> <%= p.location.address2 %>, <%= p.location.city %>, <%= p.location.state %> <%= p.location.zipcode %></b></p>             
          <hr class="soften"> 
          <p class="wrapper"><%= p.description %><span style="float: right"><%= link_to "View", p %></span></p>
        </div>
      <% end %>
      <!-- <br><br><br><br><hr>
      <div class="pagination pull-right">
        <ul>
          <li><a href="#">Prev</a></li>
          <li><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">Next &raquo</a></li>
        </ul>
      </div> -->
    </div>

app/views/properties/show.html.erb
<h1>View Listing</h1>
<br><br>
<p>
  <b>Price:</b>
  <%= @property.price %>
</p>

<p>
  <b>Sell type:</b>
  <%= @property.sell_type %>
</p>

<p>
  <b>Status:</b>
  <%= @property.status %>
</p>

<p>
  <b>Address:</b>
  <%= @property.location.address1 %><br />
  <% unless @property.location.address2.empty? %>
  <%= @property.location.address2 %><br />
  <% end %>
  <%= @property.location.city %>, <%= @property.location.state %> <%= @property.location.zipcode %>
</p>

<% unless current_buyer.nil? %>
  <%= link_to 'Apply', controller: :applications, action: :new, property_id: @property %> | 
<% end %>
<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>